name: MyStatus for Nukkit
main: cf.gamesukimanirs.mystatus.Main
version: 1.0.1
author: gamesukimanIRS
api: ["1.0.0"]
commands:
  setmessage1:
    description: ステータス上部のメッセージを設定します。(OP)
    usage: "/setmessage1 <String:メッセージ>"
  setmessage2:
    description: 画面上部のメッセージを設定します。(OP)
    usage: "/setmessage2 <String:メッセージ>"